server:
  shutdown: graceful

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  datasource:
    driver-class-name: ${DB_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: ${DB_PLATFORM}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket-name: ${AWS_BUCKET_NAME}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false

encrypt:
  secret-key: ${ENCRYPT_SECRET_KEY}